### ISSUE TITLE
"NCA rights ID unavailable" when launching through an account without permission to do so

### ISSUE THREAD

**Issue by AdalynBlack** [DarkMatterCore/nxdumptool#135]
**Describe the bug**
Original bug description:
I am attempting to dump the digital version of Mario Maker 2 off of my system, and when attempting the dump, I get the following error message: retrieveNcaTikTitleKey NCA rights ID unavailable in this console

Updated now that I understand the error better:
When trying to dump a digital game on a switch with multiple users, if you try to dump a game that isn't owned by the currently chosen user, you end up getting a strange error message that doesn't have a clear resolution. It wasn't until I started writing the bug report and realized I had done title override on the wrong title that I got on the right track to fix it. This error message should potentially be reworked to make it clear that it is required to use a user that actually owns the game when dumping. After using a user that owns the game with title override on the game, it works just fine without any issues.

**To Reproduce**
1. Enter nxdumptool through title override using a user which doesn't have permission to launch the game (launch another game with that user) (album might have the same issue, but I haven't tested it)
2. Go to `Dump installed SD card / eMMC content`
3. Select Mario Maker 2
4. Choose `Dump base application NSP`
  - Note: I am using the Yuzu recommended settings as follows:
    - Split output dump (FAT32 support): Yes
    - Verify dump using No-Intro database: No
    - Remove console specific data: Yes
    - Generate ticket-less dump: No
    - Change NPDM RSA key/sig in Program NCA: No
5. Start the dump process
6. Error Occurs Instantly

**Please fill the following information:**
- Horizon OS (Switch FW) version: 16.0.3
- CFW: Atmosphère
- CFW version: 1.5.4
- Atmosphère launch method (if applicable): Hekate
- nxdumptool version: 1.1.15
- Homebrew launch method: Title Override
- Source storage used with the application (if applicable): eMMC

**Comment by DarkMatterCore** [comment]
First and foremost, this is not a bug. Let me elaborate.

Tickets store cryptographic data used to decrypt downloaded digital titles. They are stored in a system save file and they can be easily identified using a unique rights ID. There's an additional system save file that holds a list of rights IDs from tickets that are available in the console -- if a particular rights ID isn't available there, this error will be triggered.

There are actually multiple scenarios that can trigger this particular behavior -- having multiple users available, each one owning different games, isn't the only one:

* Games shared across different consoles.
* Temporary NSO promotion titles.
* Game preloads.

In the first two cases, a rights ID match can't be found because ticket data is only downloaded (and temporarily kept in eMMC/RAM) when the game is launched. Ticket data is completely wiped after certain conditions are met (e.g. a reboot, etc.).

As for the last case, ticket data is simply not available in the first place, and it won't be until the game's release date.

On a completely different topic, I'm not really maintaining the `main` branch anymore for very personal reasons. I'm only pushing new commits to it if a HOS update breaks it, but not much more than that.

Feel free to open a PR with the revised error message if you want to. I'll merge it if you do.
