### ISSUE TITLE
Settings in new version

### ISSUE THREAD

**Issue by paulober** [DarkMatterCore/nxdumptool#142]
How can I set these settings in the new rewrite like I could in the old version:
```
For update dumps:

Split output dump (FAT32 support): Yes
Verify dump using No-Intro database: No
Remove console specific data: Yes
Generate ticket-less dump: No
Change NPDM RSA key/sig in Program NCA: No
Dump delta fragments: No


For DLC dumps:

Split output dump (FAT32 support): Yes
Verify dump using No-Intro database: No
Remove console specific data: Yes
Generate ticket-less dump: No
```

**Comment by DarkMatterCore** [comment]
Hi there. It'd have been more appropiate to open a [discussion](https://github.com/DarkMatterCore/nxdumptool/discussions) for this, but it's alright.

* `Split output dump (FAT32 support)` is no longer available -- if you're using the SD card as the output storage and the dump size exceeds `4 GiB - 1`, the output dump will now always be split using a `ConcatenationFile` entry (folder with numbered files). This is not a bug -- this is done on purpose to mimic the way Horizon OS treats files written to the SD card.

* `Verify dump using No-Intro database` is not available at the moment, but it will be reimplemented in the future, so you can just ignore that.

* `Remove console specific data` matches the `tik: remove console specific data` option.

* `Generate ticket-less dump` matches the `nca/tik: remove titlekey crypto` option. This overrides the `tik: remove console specific data` option, just like `Generate ticket-less dump` used to override `Remove console specific data` in legacy builds.

* `Change NPDM RSA key/sig in Program NCA` is no longer available because it was deemed unnecessary.

* `Dump delta fragments` is no longer available -- we discovered it never really did anything at all on legacy builds.

**Comment by paulober** [comment]
Sorry I'll create it there for other people to find in the future. And thanks for the explanation.
