### ISSUE TITLE
No option to not split dumps on rewrite version

### ISSUE THREAD

**Issue by davidheitman** [DarkMatterCore/nxdumptool#147]
Previous versions had the option to not split dumps, which was handy and timesaving when using extfat. Unless I'm missing something, this option is not present in the rewrite version. Would love to have it back, saves quite a bit of time, and one less tool to use, no need for nxdumpfuse.

**Comment by DarkMatterCore** [comment]
The option was removed because output dumps are now automatically split using `ConcatenationFile` entries (folders with numbered files) if the file size is >= 4 GiB, in order to replicate the way the rest of the Switch OS deals with big files. Even while using exFAT, this is official behavior.

Furthermore, you shouldn't really be using exFAT on the Switch, especially if you're running homebrew applications on a regular basis, because is it very prone to filesystem corruption -- not only because there's no backup FAT on exFAT, but also due to the way Nintendo's FS driver works.

If you want to dump big files if one go, setup USB dumping on your PC and use `usb host (pc)` as the output storage:

> 01. Download the latest archive of the Rewrite NROs from <https://github.com/DarkMatterCore/nxdumptool/releases/tag/rewrite-prerelease>, and copy them to your SD card, somewhere in the `switch/` directory.
> 02. Open the NRO on your console
> 03. Plug the console in via USB
> 04. Download Zadig (from <https://zadig.akeo.ie/>) and open it. It will require Administrator rights to run, as it needs to install a driver. 
> 05. Open Zadig, and select the device named `nxdt_poc_rw`.
> 06. Change the `WinUSB` entry on the "Driver" line to `libusbK`, and then hit the button below that labeled "Install Driver"
> 07. Unplug the USB cable and then plug it back in.
> 08. Use the Host EXE (from https://discord.com/channels/770369219266084945/770425806635794442/1173007226374475827 )
> 09. Click the big "Start Server" button
> 10. On your console, change the "Output Storage" setting to `usb host (pc)`
> 11. Start dump on your console, and watch it transfer directly to your machine!
