### ISSUE TITLE
Mariko_kek unavailable

### ISSUE THREAD

**Issue by docwh010** [DarkMatterCore/nxdumptool#173]
**To Reproduce**
1. Go to Homebrew Menu
2. Click on nxdt tool
3. See error

**Please fill the following information:**
- Horizon OS 19.0 version: 19.0
- CFW: Atmosphere
- CFW version: 1.8.0
- Atmosphère launch method (if applicable): Hekate
- nxdumptool version: nxdumptool-rewrite
- Homebrew launch method: Title Overide
- Source storage used with the application (if applicable): SDCard
- SD card specs: 256 Fat32 Sandisk

**Screenshots**
Error is the same as the screenshot

**Logfile**
[nxdt_rw_poc.log](https://github.com/user-attachments/files/17610557/nxdt_rw_poc.log)

**Comment by DarkMatterCore** [comment]
Hi there. This is not a bug.

Please redump your console keys using a newer Lockpick_RCM build. We won't tell you where to get it, though -- you're on your own.

**Comment by docwh010** [comment]
So I did dump my keys and mariko keys but it still errors out I reinstalled all the firmware also and it still does not work.

**Comment by DarkMatterCore** [comment]
As I stated before, you need to find a newer Lockpick_RCM build. No need to reinstall any firmware.

Mariko keys can only be obtained by bruteforcing them on a PC. Lockpick_RCM doesn't really generate them for you.

nxdumptool uses the Mariko KEK as a fallback mechanism to derive the latest master key under Mariko units when it isn't available. And it isn't available because you're not using a newer Lockpick_RCM build.
