### ISSUE TITLE
"Invalid NCA header decryption parameters" error with games installed with Gamecard Installer NX.

### ISSUE THREAD

**Issue by ElderMuskrat** [DarkMatterCore/nxdumptool#53]
When I attempt to dump base application NSP for Pokemon Sword I get the following:

decryptNcaHeader: invalid NCA header decryption parameters!

However I have had no issue dumping the update file.

**Comment by DarkMatterCore** [comment]
The application is being rewritten from scratch using a temporary private repository to improve things such as code quality, code maintenance and code readability.

Bug reports and feature requests will remain open to keep track of what's missing as hopefully add them to the new codebase.

@ElderMuskrat I can try to fix this specific error by creating a small build if you help me test it. Feel free to send me an email or hit me up in Discord.

**Comment by DarkMatterCore** [comment]
@ElderMuskrat I still intend to make a bugfix release to correct this and some other small problems, so the userbase doesn't have to wait until I finish my rewrite.

Please let me know if you can help me out debug this problem.

**Comment by larchiviste** [comment]
I'm getting the same error when dumping games installed via Gamecard Installer by TotalJustice. That's the only instance I've gotten this error so far.

**Comment by DarkMatterCore** [comment]
@ElderMuskrat @larchiviste 

The CNMT NCA handling code in Gamecard Installer NX needed some changes. @ITotalJustice has already found the bug and fixed it - he will probably release the new version sometime in the future.

![Imgur](https://i.imgur.com/n3vu6DJ.png)

Basically, the error is triggered because the CNMT NCA from games installed using Gamecard Installer NX is missing / corrupt / inexistant. This is certainly a "bad parameter for NCA decryption".

I will rename the issue and close it for now.
