### ISSUE TITLE
i keep getting parsebktrentryfromnca: invalid nca bktr subsection header size!

### ISSUE THREAD

**Issue by XMoonLightShadowsX** [DarkMatterCore/nxdumptool#62]
whenever i try to dump lets go pikachu from the game card it comes up with parsebktrentryfromnca: invalid nca bktr subsection header size! an i have no idea what it means

**Comment by DarkMatterCore** [comment]
@XMoonLightShadowsX Hi there, mate. Nice to meet you.

Please provide additional information about your current setup. Otherwise, it's very difficult for me to identify the source of your problem. Issue templates are available while [creating a new issue](https://github.com/DarkMatterCore/nxdumptool/issues/new/choose) for this very reason.

**Comment by DarkMatterCore** [comment]
@XMoonLightShadowsX I will tentatively close this issue for the time being. If you gather the required info, feel free to reopen it.
