### ISSUE TITLE
Dump to HDD

### ISSUE THREAD

**Issue by tamodolo** [DarkMatterCore/nxdumptool#75]
**Is your feature request related to a problem? Please describe.**
This is something that would facilitate part-less dumps on systems that don't have exFAT. By formating an external HDD to exFAT one could dump direct to it by connecting the HDD directly to NS.

**Describe the solution you'd like**
An option to select Dump folder to select a HDD folder.

**Describe alternatives you've considered**
I saw a USB to PC method in other issue but I didn't check if it's commited or how it works. This method is more complicated and need more work to be done.

**Additional context**
It's for convenience. Dumping directly to internal memory is a bit of a pain. External storage is the holy grail I supose.

**Comment by DarkMatterCore** [comment]
Already implemented as part of the ongoing [rewrite](https://github.com/DarkMatterCore/nxdumptool/tree/rewrite). It's not going to be implemented in legacy nxdumptool, though (current `master` branch).

Some of the PoC builds available in the Discord server are already capable of dumping data to USB mass storage devices.

Keep in mind I'm the lead developer of [libusbhsfs](https://github.com/DarkMatterCore/libusbhsfs) - the library exists just because I want this to be an actual feature in nxdumptool. :P 

I'll leave the issue open until the rewrite is officially released.

**Comment by tamodolo** [comment]
oh! Thanks for that! I'll try some of discord build then.
